# Generated by Django 5.0.4 on 2024-04-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='aadhaar_number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='created_by',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='uan_num',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='uan_status',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='unique_id',
            field=models.CharField(max_length=500),
        ),
    ]
