# Generated by Django 5.0.4 on 2024-04-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_unique_id_userdata_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='updated_date',
        ),
    ]
