# Generated by Django 5.0.4 on 2024-04-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userdata_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('father_husband_name', models.CharField(max_length=100)),
                ('relationship_with_member', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=50)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('name_as_on_aadhaar', models.CharField(max_length=100)),
                ('mr_mrs', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('wages_as_on_joining', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
