# Generated by Django 5.0.4 on 2024-04-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_excelmodel_delete_yourmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelmodel',
            name='wages_as_on_joining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
