# Generated by Django 5.0.4 on 2024-04-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_excelmodel_wages_as_on_joining'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExcelModel',
            new_name='sampledata',
        ),
    ]
