# Generated by Django 5.0.4 on 2024-04-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_excelmodel_sampledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledata',
            name='Universal_Account',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
