# Generated by Django 5.0.4 on 2024-04-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_sampledata_universal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
