# Generated by Django 5.0.4 on 2024-04-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_userdata_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='created_date',
            field=models.DateTimeField(default='<function now at 0x70fba52e9da0>', editable=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='updated_date',
            field=models.DateTimeField(default='<function now at 0x70fba52e9da0>', editable=False),
        ),
    ]
