# Generated by Django 5.0.4 on 2024-04-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_userdata_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='created_date',
            field=models.DateTimeField(default='<function now at 0x7c0a4a145da0>', editable=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='updated_date',
            field=models.DateTimeField(default='<function now at 0x7c0a4a145da0>', editable=False),
        ),
    ]
