# Generated by Django 5.0.4 on 2024-04-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_userdata_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='updated_date',
        ),
    ]
