# Generated by Django 5.0.4 on 2024-04-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_userdata_created_date_userdata_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='updated_date',
        ),
    ]
