# Generated by Django 5.0.4 on 2024-04-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_userdata_created_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sampledata',
        ),
    ]
