# Generated by Django 5.0.4 on 2024-04-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_uploadedfile_remove_userdata_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sampledata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Universal_Account', models.CharField(max_length=100)),
                ('member_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('father_husband_name', models.CharField(max_length=100)),
                ('relationship_with_member', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=50)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('name_as_on_aadhaar', models.CharField(max_length=100)),
                ('mr_mrs', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('wages_as_on_joining', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
