# Generated by Django 5.0.4 on 2024-04-28 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_sampledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='individualuserstatus',
            name='created_by',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='individualuserstatus',
            name='current_index',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='individualuserstatus',
            name='member_details',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='individualuserstatus',
            name='member_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='individualuserstatus',
            name='status',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='individualuserstatus',
            name='total_index',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='token',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='Universal_Account',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='aadhaar_number',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='date_of_joining',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='father_husband_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='marital_status',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='member_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='mr_mrs',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='name_as_on_aadhaar',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='nationality',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='relationship_with_member',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='wages_as_on_joining',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='error_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='aadhaar_number',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='remarks',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='uan_num',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='uan_status',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_uuid',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
