# Generated by Django 5.0.4 on 2024-04-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_userdata_created_date_userdata_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledata',
            name='wages_as_on_joining',
            field=models.IntegerField(default=None, max_length=10),
        ),
    ]
