# Generated by Django 5.0.4 on 2024-04-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_sampledata_wages_as_on_joining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='created_by',
        ),
    ]
