# Generated by Django 5.0.4 on 2024-04-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_userdata_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualuserstatus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='updated_date',
        ),
    ]
