# Generated by Django 5.0.4 on 2024-04-29 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_individualuserstatus_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
