# Generated by Django 5.0.4 on 2024-04-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_userdata_created_date_userdata_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledata',
            name='wages_as_on_joining',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
