# Generated by Django 5.0.4 on 2024-05-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_userdata_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sampledata',
            name='created_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sampledata',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        )
       
    ]
