# Generated by Django 5.0.4 on 2024-05-01 12:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_sampledata_created_at_sampledata_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(      
            model_name='individualuserstatus',
            name='user_data_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.sampledata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='created_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='uan_num',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_uuid',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
