# Generated by Django 5.0.4 on 2024-05-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_individualuserstatus_user_data_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledata',
            name='Universal_Account',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
