# Generated by Django 5.0.4 on 2024-05-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_sampledata_universal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='time_difference',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
