# Generated by Django 5.0.4 on 2024-05-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_userdata_time_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='time_taken',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
