# Generated by Django 5.0.4 on 2024-05-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_userdata_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='time_taken',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
