# Generated by Django 5.0.4 on 2024-05-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_remove_userdata_time_taken_userdata_time_difference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='time_difference',
        ),
    ]
