# Generated by Django 5.0.4 on 2024-05-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_remove_userdata_time_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='time',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
