# Generated by Django 5.0.4 on 2024-05-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_userdata_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampledata',
            name='mr_mrs',
        ),
    ]
