# Generated by Django 5.0.4 on 2024-05-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_remove_sampledata_mr_mrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledata',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default=None, max_length=7),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='marital_status',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='member_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='name_as_on_aadhaar',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='nationality',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
