# Generated by Django 5.0.4 on 2024-05-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_sampledata_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.AddField(
            model_name='userdata',
            name='entry_status',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='userdata',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
