# Generated by Django 5.0.4 on 2024-05-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_remove_mymodel_user_delete_uploadedfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='time',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='uan_num',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='uan_status',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user_uuid',
        ),
    ]
