# Generated by Django 5.0.4 on 2024-05-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_userdata_created_by_userdata_created_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndividualUserStatus',
        ),
    ]
