# Generated by Django 5.0.6 on 2024-05-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_delete_individualuserstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledata',
            name='is_failed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
