# Generated by Django 5.0.6 on 2024-05-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_sampledata_is_failed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='output',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='entry_status',
            new_name='entity_status',
        ),
    ]
